version: "3.8"

services:
  directus:
    image: directus/directus:latest
    container_name: directus
    ports:
      - "8055:8055"
    environment:
      - DB_CLIENT=pg
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=taskmate
      - DB_USER=postgres
      - DB_PASSWORD=123456789
      - NODE_ENV=production
      - CORS_ORIGINS=http://localhost:5173
      - API_URL=http://localhost:8055
    depends_on:
      - postgres # Ensures PostgreSQL service starts before Directus
    restart: unless-stopped # Automatically restarts if the container crashes

  postgres:
    image: postgres:latest # Use the official PostgreSQL image
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres # PostgreSQL username
      - POSTGRES_PASSWORD=123456789 # PostgreSQL password
      - POSTGRES_DB=taskmate # Name of the database
    ports:
      - "5432:5432" # Exposes PostgreSQL on port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Use a dedicated volume for PostgreSQL data
    restart: unless-stopped # Automatically restarts if the container crashes

volumes:
  postgres_data:
#z__pULZb335B
